version: '3.8'
services:
  kestra:
    image: kestra/kestra:latest
    ports:
      - "8080:8080"
    volumes:
      - ./flows:/app/flows
      - ./kestra.yml:/app/config.yml        # Mount custom config
      - kestra-data:/app/storage
    environment:
      - KESTRA_CONFIGURATION_FILE=/app/config.yml  # Point to it

volumes:
  kestra-data:
