# This is the kestra flow file
name: Deploy Kestra Flow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name : Download Kestra CLI
        run: |
           curl -L https://github.com/kestra-io/kestra/releases/download/v0.23.1/kestra-linux-amd64
  
     
      - name : Make kestra execuatable
        run: |
           chmod +x kestra
      - name : Create kestra bin director
        run: |
           mkdir -p ~/.kestra/bin
      - name : Move kestra binary
        run: |
           mv kestra ~/.kestra/bin/  
      - name : Add kestra to PATH
        run: |
           echo "$HOME/.kestra/bin" >> $GITHUB_PATH   

      - name: Verify Kestra CLI Install
        run: |
          ls -l ~/.kestra/bin/
          ~/.kestra/bin/kestra version

      - name: Authenticate with Kestra
        env:
          KESTRA_API_URL: ${{ secrets.KESTRA_API_URL }}
          KESTRA_API_USERNAME: ${{ secrets.KESTRA_API_USERNAME }}
          KESTRA_API_PASSWORD: ${{ secrets.KESTRA_API_PASSWORD }}
        run: |
          ~/.kestra/bin/kestra auth login --username $KESTRA_API_USERNAME --password $KESTRA_API_PASSWORD --url $KESTRA_API_URL

      - name: Deploy Kestra Flow
        run: |
          ~/.kestra/bin/kestra flow create flows/kube-green-scheduler.yaml
