# This is the kestra fflow file
name: Deploy Kestra Flow

on:
  push:
    paths:
      - 'flows/**.yaml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name : Download Kestra CLI
        run: |
           curl -L https://github.com/kestra-io/kestra/releases/latest/download/kestra-linux-amd64 -o kestra
           chmod +x kestra 
           mkdir -p ~/.kestra/bin
           mv kestra ~/.kestra/bin/
           echo "$HOME/.kestra/bin" >> $GITHUB_PATH   

      - name: Verify Kestra CLI Install
        run: |
          ls -l .kestra/bin/
          .kestra/bin/kestra version

      - name: Authenticate with Kestra
        env:
          KESTRA_API_URL: ${{ secrets.KESTRA_API_URL }}
          KESTRA_API_USERNAME: ${{ secrets.KESTRA_API_USERNAME }}
          KESTRA_API_PASSWORD: ${{ secrets.KESTRA_API_PASSWORD }}
        run: |
          kestra auth login --username $KESTRA_API_USERNAME --password $KESTRA_API_PASSWORD --url $KESTRA_API_URL

      - name: Deploy Kestra Flow
        run: |
          kestra flow create flows/kube-green-scheduler.yaml
